port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: AKUN VIP
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    uuid: eea95f0e-35e4-41ef-82cd-c9f8950fa9be
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vipgpi.det.my.id
    network: ws
    ws-opts:
      path: /trojan-ws
      headers:
        Host: vipgpi.det.my.id
    udp: true
  - name: AKUN2
    type: trojan
server: quiz.int.vidio.com
port: 443
password: eea95f0e-35e4-41ef-82cd-c9f8950fa9be
udp: true
sni: vipgpi.det.my.id
skip-cert-verify: true
network: grpc
grpc-opts:
grpc-service-name: trojan-grpc
    udp: true
  - name: AKUN3
    type: trojan
server: quiz.int.vidio.com
port: 443
password: eea95f0e-35e4-41ef-82cd-c9f8950fa9be
udp: true
sni: vipgpi.det.my.id
skip-cert-verify: true
network: grpc
grpc-opts:
grpc-service-name: trojan-grpc

proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AKUN TROJAN VIP
      - AKUN2
      - AKUN3

  - name: MIX-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AKUN1
      - AKUN2
      - AKUN3
      
  - name: IKLAN
    type: select
    proxies:
     - MIX-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,MIX-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,MIX-X
 - RULE-SET,Streaming,MIX-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,MIX-X
 - RULE-SET,Meta,MIX-X
 - RULE-SET,PortGame,GAME
 - MATCH,MIX-X


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  

